# Generated by Django 3.0.3 on 2020-08-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='days',
            field=models.CharField(default='nil', max_length=200),
        ),
        migrations.AlterField(
            model_name='stores',
            name='end_hour',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='start_hour',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
