# Generated by Django 3.0.3 on 2020-08-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20200812_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='day',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='day',
        ),
    ]
